name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: 'Node ${{ matrix.node-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]

    env:
      MISE_NODE_VERSION: ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: jdx/mise-action@v4
      - name: install dependencies
        run: npm ci
      - run: npm test

  release-it-compat:
    name: 'release-it@${{ matrix.release-it-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-it-version:
          ['^17.0.0', '^18.0.0', '^19.0.0']

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: jdx/mise-action@v4
      - name: install dependencies
        run: npm ci
      - run: npm install --saveDev release-it@${{ matrix.release-it-version }}
      - run: npm test
